#cloud-config

runcmd:
    - /usr/bin/configureminio.sh
    - /usr/bin/syncfiles.sh
    - chmod +x /minio/deployment-compose/powerdns/install.sh
    - chmod +x /minio/helper-scripts/*.sh
    - /minio/helper-scripts/fix-dns.sh
    - cd /minio/deployment-compose/powerdns
    - /minio/deployment-compose/powerdns/install.sh
