#cloud-config

runcmd:
    - /usr/bin/configureminio.sh
    - /usr/bin/syncfiles.sh
    - chmod +x /minio/build/deployment-compose/powerdns/install.sh
    - /minio/build/deployment-compose/powerdns/install.sh
